### ISSUE TITLE
The package is not working with symfony >3.1

### ISSUE THREAD

**Issue by ahmed-bhs** [coderspotting/toast-message#1]
> [InvalidArgumentException]
>   Could not find package coderspottingtoast-message at any version for your m
>   inimum-stability (stable). Check the package spelling or your minimum-stabi
>   lity
>

**Comment by bderidder** [comment]
Sorry for the delay, I seem to have missed the notification emails for this issue.

It's fixed in d059126bf1f978499a0ff3c4f4791d033cc83478, release 1.2 has been created and available on packagist.
